apiVersion: v1
kind: ReplicationController
metadata:
  name: bitunnel-jobq-handler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: bitunnel-jobq-handler
        image: docker.io/tradedepot/bitunnel-jobq-handler:latest
        ports:
        - containerPort: 80
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: REDIS_MASTER
          value: "${REDIS_MASTER}"
        - name: REDIS_PORT
          value: "${REDIS_PORT}"
        - name: MIDDLEWARE_EVENT_URL  
          value: "${MIDDLEWARE_EVENT_URL}"
        - name: ODATA_JOBQ_URL
          value: "${ODATA_JOBQ_URL}"
        - name: ODATA_JOBQ_USER
          value: "${ODATA_JOBQ_USER}"
        - name: ODATA_JOBQ_PASS
          value: "${ODATA_JOBQ_PASS}?"
        - name: ODATA_JOBQ_DOMAIN
          value: "${ODATA_JOBQ_DOMAIN}"
        - name: TENANT_ID
          value: "${TENANT_ID}"