apiVersion: v1
kind: ReplicationController
metadata:
  name: bitunnel-jobq-handler-${CIRCLE_BUILD_NUM}
spec:
  replicas: 1
  selector:
    app: bitunnel-png
    buildVersion: "build-${CIRCLE_BUILD_NUM}"
  template:
    metadata:
      labels:
        app: bitunnel-jobq-handler
        buildVersion: "build-${CIRCLE_BUILD_NUM}"
    spec:
      containers:
      - name: bitunnel-jobq-handler
        image: ${EXTERNAL_REGISTRY_ENDPOINT}/bitunnel-jobq-handler:build-${CIRCLE_BUILD_NUM}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: REDIS_MASTER
          value: "${SANDBOX_REDIS_MASTER}"
        - name: REDIS_PORT
          value: "${SANDBOX_REDIS_MASTER}"
        - name: MIDDLEWARE_EVENT_URL
          value: "${MIDDLEWARE_EVENT_URL}"
        - name: ODATA_JOBQ_URL
          value: "${ODATA_JOBQ_URL}"
        - name: ODATA_JOBQ_USER
          value: "${PNG_NAV_USER}"
        - name: ODATA_JOBQ_PASS
          value: "${PNG_NAV_PASS}"
        - name: ODATA_JOBQ_DOMAIN
          value: "${ODATA_JOBQ_DOMAIN}"
        - name: TENANT_ID
          value: "${PNG_TDC_TENANT_ID}"
        - name: BATCH_SIZE
          value: "${BATCH_SIZE}"