apiVersion: v1
kind: Service
metadata:
  name: bitunnel-jobq-handler
  labels:
    app: bitunnel-jobq-handler
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bitunnel-jobq-handler